spring:
  application:
    name: terrible-api-service

server:
  port: 8081

terrible:
  index: media
  task-processor:
    scheme: http
    host: localhost
    port: 8080
  search-service:
    scheme: http
    host: localhost
    port: 8082
