spring:
  application:
    name: terrible-api-service

  cloud:
    stream:
      bindings:
        apiChannel:
          destination: terrible-api-service
          group: terrible-api-service
        apiChannelThumbnail:
          destination: terrible-api-service-thumbnail
          group: terrible-api-service

server:
  port: 8081

terrible:
  index: media
  task-processor:
    scheme: http
    host: localhost
    port: 8083
  search-service:
    scheme: http
    host: localhost
    port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
